# Generated by Django 4.2 on 2023-04-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE_SUST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=30)),
                ('youtube_url', models.CharField(default=' ', max_length=200)),
                ('spotify_url', models.CharField(default=' ', max_length=200)),
                ('google_podcast_url', models.CharField(default=' ', max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='events',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='from_link',
        ),
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='subject',
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='event_year',
            field=models.CharField(default=' ', max_length=400),
        ),
        migrations.AddField(
            model_name='events',
            name='mini_description',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='show_photo',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.CreateModel(
            name='ImageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=' ', max_length=200)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IEEE_SUST.events')),
            ],
        ),
    ]
