# Generated by Django 4.2 on 2023-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE_SUST', '0002_podcast_remove_events_brief_remove_events_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='sound_cloud',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
