# Generated by Django 4.2 on 2023-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE_SUST', '0003_podcast_sound_cloud_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_year',
            field=models.CharField(default=' ', max_length=4),
        ),
    ]
