# Generated by Django 4.2 on 2023-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE_SUST', '0004_alter_events_event_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='show_photo',
            field=models.ImageField(upload_to='Image'),
        ),
        migrations.AlterField(
            model_name='imageevent',
            name='image',
            field=models.ImageField(upload_to='Image'),
        ),
    ]
