# Generated by Django 4.2 on 2023-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE_SUST', '0006_alter_events_show_photo_alter_imageevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='show_photo',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='imageevent',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
